### ISSUE TITLE
A minor improve for open tiles from a texture.

### ISSUE THREAD

**Issue by Ahtram** [StalinGD/QuickRuleTileEditor#1]
Hi, thanks for the cool package!

Here's the quick result for what I did.
![2024-10-31_02-39](https://github.com/user-attachments/assets/1d8c1ace-ba7b-4ec0-baa5-7bf3720ceae1)

This could make the workflow even better for me.

What I did:
I simple change the  GetSpritesFromTexture function in Utilities.cs to this:

```
        public static IEnumerable<Sprite> GetSpritesFromTexture(Object texture) {
            var path = AssetDatabase.GetAssetPath(texture);
            Object[] subAssets = AssetDatabase.LoadAllAssetsAtPath(path);

            //Sort the Sprites by their name's trail number.
            subAssets = subAssets.OrderBy(x => {
                string indexStr = x.name.Substring(x.name.LastIndexOf('_') + 1);
                int index = 0;
                int.TryParse(indexStr, out index);
                return index;
            }).ToArray();

            return subAssets.OfType<Sprite>();
        }
```

have a nice day!

**Comment by stalengd** [comment]
@Ahtram Hey, glad to see that someone really using this tool and thanks for contribution!
But you just created an issue, this github feature is not intended for code proposals, please create a [Pull Request](https://github.com/stalengd/QuickRuleTileEditor/pulls) with your change, there are plenty of guides how to do this and I think you will have no problems of doing this. You can even probably create pull request just with github webpage, without dealing with cloning repository to your machine.
